server:
  port: 8001
spring:
  application:
    name: cloud-provider-hystrix-payment

eureka:
  client:
    #表示是否将自己注册进eurekaService服务器，默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
#  instance:
#    instance-id: payment8001 #修改主机名称
#    prefer-ip-address: true #点主机名称出现ip地址
#    #Eureka客户端向服务端发送心跳的时间间隔（默认30秒）
#    lease-renewal-interval-in-seconds: 1
#    #Eureka服务端在收到最后一次心跳等待的时间上限，单位为秒（默认90秒），超时将剔除服务
#    lease-expiration-duration-in-seconds: 2
